### PR TITLE
Convert to component

### PR DESCRIPTION
**Pull request by chmorgan**
Hi Dave.

Here is the first step. I'm waiting on hardware to be able to test the changes but not much was changed.

One question I had was how easy it would be to switch the sampling window and period from seconds to milliseconds or would that not make sense? Not that I can't get by with seconds but it would be helpful I think for shorter periods and windows.

### CODE REVIEW

**Comment by DavidAntliff** [comment]
Thanks for this. Feel free to grab stuff from my esp32-poolmon project as you see fit, it's all under the same license.

To try to answer your question: there's a trade-off between window size and frequency resolution (the uncertainty principle). This way of measuring frequency is by counting wavelengths over a fixed window, so the smaller the window, the less precise the measured value will be. This is because you need to see at least one full wavelength (or at least half of one if you know the duty cycle) to measure it. For example, with a 1 second window, your precision is only around 1 Hz. You need to observe for 10 seconds to get 0.1 Hz resolution. 

The code actually does support frequencies up to about 16 MHz. You need to configure the glitch filter appropriately (be careful of non-50/50 duty cycles) and then set the sample period to, say, 1 millisecond.

```
// suitable up to 16,383,500 Hz - no filter
#define SAMPLE_PERIOD 0.001  // seconds
#define FILTER_LENGTH 0  // APB @ 80MHz, limits to < 40 MHz
```

Ideally the component would let the user configure this at runtime, perhaps by giving a frequency range that they are interested in, or perhaps by just specifying the sample period and filter length explicitly, rather than as compiler definitions. Perhaps that's the best place to start?

**Comment by DavidAntliff** [comment]
Let me know when you feel this is in a fit state for me to review and merge. Usually I create an example project alongside a component, so I will write a simple one once this is ready to "ship". Thanks for your efforts.

**Comment by chmorgan** [comment]
Hi David.

Sure thing. I don’t have hardware that uses a fan yet so I haven’t been
able to test. And I’ll probably push a version that takes in a frequency
range and reports status or accuracy or something as a helper. Haven’t
gotten that far yet but if I end up not needing a fan then I’ll let you
know in case you want to set up a test case of hardware. That’s the
limitation I have now. I don’t have an external frequency generator.
Although I could use the scope test/calibration signal...

**Comment by chmorgan** [comment]
Hi @DavidAntliff, I've tested this here and its working well for my use case. Interested in merging this and pulling in the example repo where I've put the example application code?

**Comment by DavidAntliff** [comment]
Hi @chmorgan, this looks good - thank you. I want to give myself a bit of time to sit down with hardware and understand the changes, so I'll merge it once I've had that chance to do that.

**Comment by chmorgan** [comment]
Hi @DavidAntliff checking in again on this pr to see how I can get it merged back in.

**Comment by DavidAntliff** [comment]
Hi Chris, my apologies, this has been on my TODO list but I haven't managed to fit it in yet. It's still something I intend to review properly and will most likely merge. I haven't made any changes to the original project in the meantime so your fork should be OK for now, but I will try to look into it soon.

**Comment by DavidAntliff** [comment]
@chmorgan I'm going to merge this now and then construct an example repository, as per my usual pattern of component & example. I see that you've prepped an example repo in your namespace but as far as I can tell it hasn't progressed yet. If it's OK with you I'll go ahead with my example, based on your componentization, and we can go from there? Hope that sounds OK.

**Comment by DavidAntliff** [comment]
WIP here: https://github.com/DavidAntliff/esp32-freqcount-example

**Comment by chmorgan** [comment]
Hi David.

Thanks for merging the other code.

I did move the example code over and it should be buildable and using the
other module as a component,

https://github.com/chmorgan/esp32-freqcount?files=1

**Comment by chmorgan** [comment]
Or maybe not... it’s  been a while. I’ll have to look locally tomorrow to
see if I have other changes there that I didn’t push yet.

**Comment by DavidAntliff** [comment]
No problem, I've just completed an example with some minor changes to the component so I'll push those shortly and you can compare with yours - if you have the time/energy we can combine for the best result :)

**Comment by DavidAntliff** [comment]
Preliminary version here: https://github.com/DavidAntliff/esp32-freqcount-example/commit/45ef4c61125d0ad7ad11feebdfbf95844a2791c5
Seems to be working fine with your "componentized" version - thank you for doing this, it should be a useful module to have around.

**Comment by DavidAntliff** [comment]
BTW I added a "RMT max blocks" parameter since RMT lets you use more than 64 items if you are prepared to let it use adjacent blocks. For example, the default config uses about 77 items, which spans two blocks.

**Comment by DavidAntliff** [comment]
@chmorgan ok, I'm pretty much done with the example and component for today - please take a look at the result and let me know if you're happy with the outcome. If you want to suggest any changes another PR is always welcome. Thanks for your patience.

**Pull request merged**
